/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_rover_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

/* ocp_rover_expl_vde_forw:(i0[2],i1[2x2],i2[2x3],i3[3],i4[11])->(o0[2],o1[2x2],o2[2x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=9.8100000000000005e+00;
  a1=arg[4]? arg[4][6] : 0;
  a2=sin(a1);
  a2=(a0*a2);
  a3=arg[4]? arg[4][5] : 0;
  a2=(a2/a3);
  a4=arg[4]? arg[4][8] : 0;
  a5=1.1772040000000001e+01;
  a6=(a5*a3);
  a6=(a4/a6);
  a2=(a2+a6);
  a6=arg[4]? arg[4][2] : 0;
  a7=cos(a6);
  a8=3.5000000000000003e-02;
  a9=(a5*a3);
  a9=(a8*a9);
  a7=(a7/a9);
  a9=arg[4]? arg[4][9] : 0;
  a7=(a7*a9);
  a2=(a2+a7);
  a7=arg[4]? arg[4][3] : 0;
  a10=cos(a7);
  a11=(a5*a3);
  a11=(a8*a11);
  a10=(a10/a11);
  a11=arg[4]? arg[4][10] : 0;
  a10=(a10*a11);
  a2=(a2+a10);
  a0=(a0/a3);
  a10=cos(a1);
  a0=(a0*a10);
  a10=arg[0]? arg[0][0] : 0;
  a10=(a10-a1);
  a10=(a0*a10);
  a1=arg[3]? arg[3][0] : 0;
  a1=(a1-a4);
  a4=(a5*a3);
  a1=(a1/a4);
  a6=cos(a6);
  a5=(a5*a3);
  a8=(a8*a5);
  a6=(a6/a8);
  a5=arg[3]? arg[3][1] : 0;
  a5=(a5-a9);
  a5=(a6*a5);
  a1=(a1+a5);
  a7=cos(a7);
  a7=(a7/a8);
  a8=arg[3]? arg[3][2] : 0;
  a8=(a8-a11);
  a8=(a7*a8);
  a1=(a1+a8);
  a10=(a10+a1);
  a2=(a2+a10);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a2;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][1]=a2;
  a2=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a2;
  a2=arg[1]? arg[1][2] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][3]=a2;
  a2=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a2;
  a4=(1./a4);
  a2=arg[2]? arg[2][0] : 0;
  a2=(a0*a2);
  a4=(a4+a2);
  if (res[2]!=0) res[2][1]=a4;
  a4=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][2]=a4;
  a4=arg[2]? arg[2][2] : 0;
  a4=(a0*a4);
  a6=(a6+a4);
  if (res[2]!=0) res[2][3]=a6;
  a6=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][4]=a6;
  a6=arg[2]? arg[2][4] : 0;
  a0=(a0*a6);
  a7=(a7+a0);
  if (res[2]!=0) res[2][5]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_rover_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_rover_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_rover_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_rover_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_rover_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_rover_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_rover_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_rover_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_rover_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_rover_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ocp_rover_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_rover_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_rover_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_rover_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_rover_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_rover_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
